---
# tasks file for setup-docker 
- name: Download Docker GPG key
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'
    force: yes

- name: Add Docker APT repository
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_facts['distribution_release'] }} stable"
    state: present
    filename: docker
  register: docker_repo

- name: Update apt cache after adding Docker repo
  apt:
    update_cache: yes
  when: docker_repo.changed

- name: Install Docker and dependencies
  apt:
    name:       
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
  

- name: Ensure Docker is enabled and running
  service:
    name: docker
    state: started
    enabled: yes

- name: Add vagrant user to docker group
  user:
    name: "{{ docker_user }}"
    groups: docker
    append: yes
  notify: Restart docker

- name: Verify Docker installation
  command: docker version
  register: docker_check
  changed_when: false
  failed_when: docker_check.rc != 0
